services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
